### ISSUE TITLE
Renderer resize default value

### ISSUE THREAD

**Issue by christian-nils** [troisjs/troisjs.github.io#2]
Hi @klevron,

When reading the documentation, it is written that the resize props of the renderer has a default value set to "window":

![image](https://user-images.githubusercontent.com/2658014/110027947-ec3a1b80-7d32-11eb-8a9f-ec0258989dd1.png)

But looking at the source file, it seems to be "true", and not "window". If I am not mistaken, that typo might need to be fixed on the guide.

![image](https://user-images.githubusercontent.com/2658014/110028118-24415e80-7d33-11eb-8c6a-e8fe42eeb805.png)

Thanks!

/CN

**Comment by klevron** [comment]
Thanks for reporting this, I am not sure actually what should be the default value, may be false ?

- false : no resizing
- true : parent size
- 'window' : window size

**Comment by christian-nils** [comment]
Personally, I would rather have "false". 
But if the bullet list you just wrote was in that table, it would already have been much more straightforward.
